VEHICLE_PLANE = 1
VEHICLE_HELICOPTER = 2
VEHICLE_VTOL = 3
VEHICLE_BOAT = 4
VEHICLE_TANK = 5
VEHICLE_WEAPON = 6
VEHICLE_WARBIRD = 7
VEHICLE_SPACECRAFT = 8
VEHICLE_SUBMARINE = 9

WEAPON_MISSILE = 20
WEAPON_ROCKET = 21
WEAPON_BOMB = 22
WEAPON_GUN = 23
STATIC_GUN = 23
WEAPON_TURRET = 23
WEAPON_TORPEDO = 20
WEAPON_MINE = 25
